// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq3j5CFnIZUKx-j1L9yFA2IApzbQCXoNU',
    appId: '1:1028080843947:web:be1be94c133f5624cacbee',
    messagingSenderId: '1028080843947',
    projectId: 'scarpa-2026',
    authDomain: 'scarpa-2026.firebaseapp.com',
    databaseURL: 'https://scarpa-2026-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scarpa-2026.firebasestorage.app',
    measurementId: 'G-B11PPZZ61X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfdgR_p624C9eKU1m5PsUBvKscnNW0wLc',
    appId: '1:1028080843947:android:52ac4e5d4a4a2eddcacbee',
    messagingSenderId: '1028080843947',
    projectId: 'scarpa-2026',
    databaseURL: 'https://scarpa-2026-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scarpa-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGDUbL1kQnL18_Mav8Ojkvz2hVU4YdWgg',
    appId: '1:1028080843947:ios:d9df8b2a8d0f5167cacbee',
    messagingSenderId: '1028080843947',
    projectId: 'scarpa-2026',
    databaseURL: 'https://scarpa-2026-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'scarpa-2026.firebasestorage.app',
    iosBundleId: 'com.rivas.scarpa',
  );
}
